---
- name: "Restart openshift master and node with locally built ose binaries"
  hosts: OSEv3
  remote_user: root
  roles:
  - sync_origin_restart_with_local_built
  tags: sync_origin_restart_with_local_built

